package io.openems.edge.rctpower.ess;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.rctpower.enums.ControlMode;

@ObjectClassDefinition(//
		name = "RCT Power ESS", //
		description = "Implements the RCT Power Energy Storage System.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;
	
	@AttributeDefinition(name = "PV-Export Limit?", description = "Send the export power site limit to the inverter.")
	boolean pvExportLimit() default false;
	
	@AttributeDefinition(name = "Control mode", description = "Sets the Control mode")
	ControlMode controlMode() default ControlMode.INTERNAL;	
	
	@AttributeDefinition(name = "Rctpower-ID", description = "ID of RctPower bridge.")
	String rctpower_id() default "rctpower0";
	
	@AttributeDefinition(name = "Capacity", description = "Capacity of the battery in [Wh]")
	int capacity() default 11_520;	
	
	@AttributeDefinition(name = "Rctpower target filter", description = "This is auto-generated by 'Rctpower-ID'.")
	String Rctpower_target() default "(enabled=true)";	

	String webconsole_configurationFactory_nameHint() default "io.openems.edge.rtcpower [{id}]";

}