package io.openems.edge.rctpower.charger;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;


@ObjectClassDefinition(name = "RctPower Charger A", //
		description = "The MPP tracker A implementation of a RctPower energy storage system.")
@interface ConfigA {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "charger0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;
	
	@AttributeDefinition(name = "RctPower ESS-Inverter", description = "ID of RctPower Energy Storage System.")
	String essInverter_id() default "ess0";
	
	@AttributeDefinition(name = "RctPower ESS-Inverter target filter", description = "This is auto-generated by 'RctPower ESS-Inverter'.")
	String essInverter_target() default "(enabled=true)";	

	String webconsole_configurationFactory_nameHint() default "RctPower Charger A [{id}]";

}
